Models/Country.cs
namespace Footballer_Catalog.Models;

public enum Country
{
    Россия,
    США,
    Италия
}

Models/Footballer.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNetCore.Mvc;

namespace Footballer_Catalog.Models;

public class Footballer
{
    public int Id { get; set; }
    [Required]
    public string Name { get; set; }
    [Required]
    public string Surname { get; set; }
    [Required]
    public Gender Gender { get; set; }
    [Required]
    public DateTime Birthdate { get; set; }
    [Required]
    public Team Team { get; set; }
    [Required]
    public Country Country { get; set; }
}

Models/FootballerContext.cs
using System.Globalization;
using Microsoft.EntityFrameworkCore;

namespace Footballer_Catalog.Models;

public class FootballerContext : DbContext
{
    public DbSet<Footballer> Footballers { get; set; }

    public FootballerContext(DbContextOptions<FootballerContext> options) :
        base(options)
    {
        Database.EnsureCreated();
    }
}

Models/Gender.cs
using System.ComponentModel.DataAnnotations;

namespace Footballer_Catalog.Models;

public enum Gender
{
    Мужчина,
    Женщина
}

Models/Team.cs
using System.ComponentModel.DataAnnotations;

namespace Footballer_Catalog.Models;

public class Team
{
    public int Id { get; set; }
    [Required]
    public string Name { get; set; }
}

Controllers/FootballersController.cs
using Microsoft.AspNetCore.SignalR;
using Microsoft.AspNetCore.Mvc;
using Footballer_Catalog.Models;
using Footballer_Catalog.Services;
using Microsoft.EntityFrameworkCore;

namespace Footballer_Catalog.Controllers;

public class FootballersController : Controller
{
    private IFootballersService footballersService;
    
    public FootballersController(IFootballersService footballersService)
    {
        this.footballersService = footballersService;
    }
    
    [HttpGet]
    public async Task<IActionResult> Add()
    {
        ViewBag.Teams = (await footballersService.GetTeams()).Select(team => team.Name);
        return View();
    }
    
    [HttpPost]
    public async Task<IActionResult> Add(Footballer footballer)
    {
        if (!ModelState.IsValid)
        {
            ViewBag.Teams = (await footballersService.GetTeams()).Select(team => team.Name);
            return View(footballer);
        }
        await footballersService.Add(footballer);
        return RedirectToAction("Index", "Home");
    }

    [HttpGet]
    public async Task<IActionResult> Edit(int? id)
    {
        if (id.HasValue)
        {
            ViewBag.Teams = (await footballersService.GetTeams()).Select(team => team.Name);
            var footballer = await footballersService.GetFootballer(id.Value);
            if (footballer != null)
                return View(footballer);
        }
        return NotFound();
    }
    
    [HttpPost]
    public async Task<IActionResult> Edit(Footballer footballer)
    {
        if (!ModelState.IsValid)
        {
            ViewBag.Teams = (await footballersService.GetTeams()).Select(team => team.Name);
            return View(footballer);
        }
        await footballersService.Edit(footballer);
        return RedirectToAction("Index", "Home");
    }

    public async Task<IActionResult> Delete(int? id)
    {
        if (id.HasValue)
        {
            await footballersService.Delete(id.Value);
            return RedirectToAction("Index", "Home");
        }
        return NotFound();
    }
}

Controllers/HomeController.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Footballer_Catalog.Models;
using Footballer_Catalog.Services;

namespace Footballer_Catalog.Controllers;

public class HomeController : Controller
{
    private IFootballersService footballersService;
    public HomeController(IFootballersService footballersService)
    {
        this.footballersService = footballersService;
    }

    public async Task<IActionResult> Index()
    {
        return View(await footballersService.GetFootballers());
    }
}

Views/Footballers/Add.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@using Footballer_Catalog.Models
@model Footballer_Catalog.Models.Footballer

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <title>Добавление игрока</title>
    @Html.ActionLink("К списку игроков", "Index", "Home")
</head>
<body>
<form asp-action="Add" asp-controller="Footballers" method="post">
    <div>
        <label asp-for="Name">Имя</label>
        <input type="text" asp-for="Name" autocomplete="off" required/>
    </div>
    <div>
        <label asp-for="Surname">Фамилия</label>
        <input type="text" asp-for="Surname" autocomplete="off" required/>
    </div>
    <div>
        <label asp-for="Gender" class="control-label">Пол</label>
        @Html.DropDownList("Gender", Html.GetEnumSelectList(typeof(Gender)), "Пол")
    </div>
    <div>
        <label asp-for="Birthdate">Дата рождения</label>
        <input type="date" asp-for="Birthdate" class="form control"/>
    </div>
    <div>
        <label asp-for="Team.Name">Команда</label>
        <input type="text" asp-for="Team.Name" list="teams" autocomplete="off" required/>
        <datalist id="teams">
            @foreach (var team in ViewBag.Teams)
                {
                    <option>@team</option>
                }
        </datalist>
    </div>
    <div>
        <label asp-for="Country">Страна</label>
        @Html.DropDownList("Country", Html.GetEnumSelectList(typeof(Country)), "Страна")
    </div>
    <div class="form-group">
        <input type="submit" value="Добавить игрока"/>
    </div>
</form>
</body>
</html>

Views/Footballers/Edit.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@using Footballer_Catalog.Models
@model Footballer_Catalog.Models.Footballer

@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <title>Редактирование</title>
    @Html.ActionLink("К списку игроков", "Index", "Home")
</head>
<body>
<form asp-action="edit" asp-controller="Footballers" asp-route-id="@Model.Id">
    <div>
        <label asp-for="Name">Имя</label>
        <input type="text" asp-for="Name" value="@Model.Name" autocomplete="off" required/>
    </div>
    <div>
        <label asp-for="Surname">Фамилия</label>
        <input type="text" asp-for="Surname" value="@Model.Surname" autocomplete="off" required/>
    </div>
    <div>
        <label asp-for="Gender">Пол</label>
        @Html.DropDownList("Gender", Html.GetEnumSelectList(typeof(Gender)), "Пол", new { @value = @Model.Gender})
    </div>
    <div>
        <label asp-for="Birthdate">Дата рождения</label>
        <input type="date" asp-for="Birthdate" value="@Model.Birthdate.ToString("yyyy-MM-dd")"/>
    </div>
    <div>
        <label asp-for="Team.Name">Команда</label>
        <input type="text" asp-for="Team.Name" value="@Model.Team.Name" list="teams" autocomplete="off" required/>
        <datalist id="teams">
            @foreach (var team in ViewBag.Teams)
            {
                <option>@team</option>
            }
        </datalist>
    </div>
    <div>
        <label asp-for="Country">Страна</label>
        @Html.DropDownList("Country", Html.GetEnumSelectList(typeof(Country)), "Страна", new { @value = @Model.Country})
    </div>
    <div class="form-group">
        <input type="submit" value="Изменить данные"/>
    </div>
</form>
</body>
</html>

Views/Home/Index.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@using Footballer_Catalog.Models
@model IEnumerable<Footballer_Catalog.Models.Footballer>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <title>Футболисты</title>
    @Html.ActionLink("Добавить игрока", "Add", "Footballers")
</head>
<body>
<h3>Футболисты</h3>
<table id="footballers">
    <tr>
        <td>Имя</td>
        <td>Фамилия</td>
        <td>Пол</td>
        <td>Дата рождения</td>
        <td>Команда</td>
        <td>Страна</td>
    </tr>
    @foreach (var footballer in Model)
        {
            <tr id="@footballer.Id">
                <td name="Name">@footballer.Name</td>
                <td name="Surname">@footballer.Surname</td>
                <td name="Gender">@footballer.Gender</td>
                <td name="Birthdate">@footballer.Birthdate.ToString("dd/MM/yyyy")</td>
                <td name="Team">@footballer.Team.Name</td>
                <td name="Country">@footballer.Country</td>
                <td>
                    <a asp-controller="Footballers" asp-action="Edit" asp-route-id="@footballer.Id">Изменить</a> |
                    <a asp-controller="Footballers" asp-action="Delete" asp-route-id="@footballer.Id">Удалить</a>
                </td>
            </tr>
        }
</table>
<script src="js/signalr/dist/browser/signalr.min.js"></script>
<script>
    const hubConnection = new signalR.HubConnectionBuilder()
                .withUrl("/update")
                .build();
    

    let countries = @Html.Raw(Newtonsoft.Json.JsonConvert.SerializeObject(Enum.GetNames(typeof(Country))));
    let genders = @Html.Raw(Newtonsoft.Json.JsonConvert.SerializeObject(Enum.GetNames(typeof(Gender))))
    
            hubConnection.on("Edit", function (footballer) {
                let updatedFootballer = document.getElementById(footballer.id)
                updatedFootballer.querySelector('[name="Name"]').innerText = footballer.name
                updatedFootballer.querySelector('[name="Surname"]').innerText = footballer.surname
                updatedFootballer.querySelector('[name="Gender"]').innerText = genders[footballer.gender]
                updatedFootballer.querySelector('[name="Birthdate"]').innerText = new Date(footballer.birthdate).toLocaleDateString()
                updatedFootballer.querySelector('[name="Team"]').innerText = footballer.team.name
                updatedFootballer.querySelector('[name="Country"]').innerText = countries[footballer.country]
            });
            
            hubConnection.on("Add", function (footballer) {
                let footballers = document.getElementById('footballers').getElementsByTagName('tbody')[0]
                let newFootballer = footballers.insertRow(footballers.rows.length)
                newFootballer.setAttribute("id", footballer.id)
                let tdName = newFootballer.insertCell()
                tdName.appendChild(document.createTextNode(footballer.name))
                let tdSurname = newFootballer.insertCell()
                tdSurname.appendChild(document.createTextNode(footballer.surname))
                let tdGender = newFootballer.insertCell()
                tdGender.appendChild(document.createTextNode(genders[footballer.gender]))
                let tdBirthdate = newFootballer.insertCell()
                tdBirthdate.append(document.createTextNode(new Date(footballer.birthdate).toLocaleDateString()))
                let tdTeam = newFootballer.insertCell()
                tdTeam.append(document.createTextNode(footballer.team.name))
                let tdCountry = newFootballer.insertCell()
                tdCountry.append(document.createTextNode(countries[footballer.country]))
                let refs = newFootballer.insertCell()
                let editNode = document.createElement('a');
                let edithref = "/Footballers/Edit/" + footballer.id
                editNode.appendChild(document.createTextNode("Изменить"))
                editNode.setAttribute("href", edithref)
                refs.appendChild(editNode)
                refs.appendChild(document.createTextNode(" | "))
                let deleteNode = document.createElement('a');
                let deletehref = "/Footballers/Delete/" + footballer.id
                deleteNode.appendChild(document.createTextNode("Удалить"))
                deleteNode.setAttribute("href", deletehref)
                refs.appendChild(deleteNode)
            });
            
            hubConnection.on("Delete", function (footballerId) {   
                            let footballer = document.getElementById(footballerId)
                            footballer.remove()
                        });
            
            hubConnection.start();
</script>
</body>
</html>